#!/usr/bin/env node
// Downloads the site's four brand families from Google Fonts and writes a
// self-contained @font-face stylesheet for design-sync.
//
// Why: app/layout.tsx loads Inter, Space Grotesk, Montserrat and Cormorant
// Garamond via next/font/google, which does two things at runtime that do not
// exist outside Next -- it serves the woff2 files AND defines the CSS variables
// (--font-inter etc.) that globals.css consumes in every font-family rule.
// Neither survives into the bundle, so without this the DS pane and every design
// built with it fall back to system fonts ([FONT_MISSING] + [TOKENS_MISSING]).
//
// Output: .design-sync/fonts/*.woff2 + .design-sync/fonts/fonts.css, wired via
// cfg.extraFonts. Re-run only when the families or weights in layout.tsx change.

import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "fonts");

// Mirrors app/layout.tsx exactly.
const FAMILIES = [
	{ name: "Inter", cssVar: "--font-inter", weights: [400, 500, 600, 700, 800, 900], italic: false },
	{ name: "Space Grotesk", cssVar: "--font-space-grotesk", weights: [300, 400, 500, 600, 700], italic: false },
	{ name: "Montserrat", cssVar: "--font-montserrat", weights: [300, 400, 500, 600, 700, 800, 900], italic: false },
	{ name: "Cormorant Garamond", cssVar: "--font-cormorant", weights: [300, 400, 500, 600, 700], italic: true },
];

// A modern browser UA is required or the API serves legacy ttf instead of woff2.
const UA =
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// Keep only the Latin ranges — the site is English-only and the full set would
// multiply the payload for glyphs no design will render.
const KEEP_SUBSETS = ["latin", "latin-ext"];

function apiUrl({ name, weights, italic }) {
	const fam = name.replace(/ /g, "+");
	if (italic) {
		const spec = [...weights.map((w) => `0,${w}`), ...weights.map((w) => `1,${w}`)].join(";");
		return `https://fonts.googleapis.com/css2?family=${fam}:ital,wght@${spec}&display=swap`;
	}
	return `https://fonts.googleapis.com/css2?family=${fam}:wght@${weights.join(";")}&display=swap`;
}

// The fonts are COMMITTED (see .gitignore), so a fresh clone already has them and
// needs no network. Bail out early rather than wiping them: the documented build
// order runs this script unconditionally, and an offline run would otherwise
// rmSync 58 committed files and then exit 1 on the first fetch, leaving fonts/
// empty and build-css.mjs unable to find font-vars.css.
// Pass --force to genuinely refetch (e.g. after changing FAMILIES).
const FORCE = process.argv.includes("--force");
if (!FORCE && existsSync(join(OUT, "font-vars.css"))) {
	console.error(`[fonts] fonts/ already present — skipping fetch (use --force to refetch)`);
	process.exit(0);
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

let sheet = `/* Brand fonts for design-sync — generated by .design-sync/build-fonts.mjs.
 * Mirrors the next/font/google families in app/layout.tsx. Do not hand-edit.
 */\n\n`;
let files = 0;

for (const fam of FAMILIES) {
	const res = await fetch(apiUrl(fam), { headers: { "User-Agent": UA } });
	if (!res.ok) {
		console.error(`[fonts] ✗ ${fam.name}: HTTP ${res.status}`);
		process.exit(1);
	}
	const css = await res.text();

	// Each @font-face in the response is one (weight, style, unicode-range) face.
	const blocks = css.split("@font-face").slice(1);
	let kept = 0;
	let currentSubset = null;

	// Google annotates each face with a `/* latin */` style comment beforehand.
	const annotated = css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g);
	for (const m of annotated) {
		const subset = m[1];
		const body = m[2];
		if (!KEEP_SUBSETS.includes(subset)) continue;

		const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
		const weight = body.match(/font-weight:\s*([^;]+);/)?.[1]?.trim();
		const style = body.match(/font-style:\s*([^;]+);/)?.[1]?.trim() ?? "normal";
		const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
		if (!url || !weight) continue;

		const slug = `${fam.name.replace(/ /g, "-")}-${weight}-${style}-${subset}`.toLowerCase();
		const file = `${slug}.woff2`;
		const bin = await fetch(url, { headers: { "User-Agent": UA } });
		if (!bin.ok) {
			console.error(`[fonts] ✗ ${file}: HTTP ${bin.status}`);
			process.exit(1);
		}
		writeFileSync(join(OUT, file), Buffer.from(await bin.arrayBuffer()));
		files++;
		kept++;

		sheet += `@font-face {
  font-family: '${fam.name}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url('./${file}') format('woff2');${range ? `\n  unicode-range: ${range};` : ""}
}\n\n`;
	}
	console.error(`[fonts] ${fam.name}: ${kept} face(s) from ${blocks.length} in the API response`);
	if (!kept) {
		console.error(`[fonts] ✗ ${fam.name}: no faces kept — the API response shape may have changed`);
		process.exit(1);
	}
}

writeFileSync(join(OUT, "fonts.css"), sheet);

// The CSS variables next/font would have defined. globals.css reads these in
// every font-family rule (`font-family: var(--font-space-grotesk), var(--font-inter), sans-serif`),
// so without them the whole type system silently degrades to the fallback --
// headings in particular lose Space Grotesk entirely.
//
// These live in a SEPARATE file, not in fonts.css, because the converter parses
// cfg.extraFonts stylesheets for @font-face rules only and discards everything
// else -- a :root block in fonts.css never reaches the bundle. build-css.mjs
// appends this file to the compiled cssEntry, which IS copied verbatim.
const vars = `/* CSS variables next/font/google injects at runtime in app/layout.tsx.
 * Generated by .design-sync/build-fonts.mjs — appended to compiled.css by build-css.mjs.
 */
:root {
${FAMILIES.map((f) => `  ${f.cssVar}: '${f.name}';`).join("\n")}
}
`;
writeFileSync(join(OUT, "font-vars.css"), vars);

console.error(`[fonts] wrote ${files} woff2 + fonts.css + font-vars.css to .design-sync/fonts/`);
