#!/usr/bin/env node
// design-sync CSS build for the Trixode site.
//
// Why this exists: the repo ships NO compiled CSS. Every visual property of every
// component lives in Tailwind utility classes compiled at build time by PostCSS.
// Pointing cfg.cssEntry at styles/globals.css would ship raw `@tailwind` directives
// and every preview card would render unstyled.
//
// Two steps:
//   1. Compile styles/globals.css -> .design-sync/compiled.css via the repo's own
//      tailwindcss 3.4, using .design-sync/tailwind.sync.ts (adds previews/ to content).
//   2. Alias the dark palette onto :root. Preview cards and rendered designs have no
//      next-themes `html.dark` class, but the site's defaultTheme is "dark" and the
//      brand background is #030303 -- so light-theme cards would be off-brand.
//      The aliases are DERIVED from the compiled output (every `.dark { --x: y }`
//      token block re-emitted as `:root`), never hand-copied, so they cannot rot
//      when globals.css changes.
//
// Re-run this after authoring/editing any .design-sync/previews/*.tsx -- Tailwind only
// emits classes it saw at compile time.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const IN = "styles/globals.css";
const OUT = ".design-sync/compiled.css";
const CONFIG = ".design-sync/tailwind.sync.ts";

console.error(`[css] compiling ${IN} -> ${OUT}`);
execFileSync(
	process.execPath,
	[
		resolve(repoRoot, "node_modules/tailwindcss/lib/cli.js"),
		"--config", CONFIG,
		"--input", IN,
		"--output", OUT,
	],
	{ cwd: repoRoot, stdio: ["ignore", "inherit", "inherit"] },
);

const outPath = resolve(repoRoot, OUT);
let css = readFileSync(outPath, "utf8");

// --- step 2: derive :root dark aliases -------------------------------------
// Match blocks whose selector is EXACTLY `.dark` and whose body is nothing but
// custom-property declarations. That precision matters: Tailwind also emits
// `.dark\:bg-x:is(.dark *)` variant selectors and authors may write `.dark .foo`,
// none of which are token blocks.
const tokenBlocks = [];
const re = /(^|\})\s*\.dark\s*\{([^{}]*)\}/g;
let m;
while ((m = re.exec(css)) !== null) {
	// Strip CSS comments before classifying: these blocks carry inline notes
	// (e.g. `/* Dark Theme Variables */`) that would otherwise fail the
	// all-custom-properties test and silently drop the block.
	const body = m[2].replace(/\/\*[\s\S]*?\*\//g, "");
	const decls = body.split(";").map((s) => s.trim()).filter(Boolean);
	if (decls.length && decls.every((d) => d.startsWith("--"))) {
		tokenBlocks.push(decls.join(";\n  ") + ";");
	}
}

if (!tokenBlocks.length) {
	console.error("[css] ✗ no `.dark` token blocks found — refusing to emit light-only CSS");
	process.exit(1);
}

// Guard against silently dropping a block: every top-level `.dark {` rule in the
// compiled output should have been classified as a token block. If one wasn't, the
// palette is half-aliased and cards render partly light -- which looks plausible
// enough to pass a render check while being off-brand.
const topLevelDark = (css.match(/(^|\n)\.dark\s*\{/g) || []).length;
if (tokenBlocks.length !== topLevelDark) {
	console.error(
		`[css] ✗ found ${topLevelDark} top-level \`.dark\` rule(s) but only aliased ${tokenBlocks.length}. ` +
		`A token block was dropped — the palette would be half-light. Inspect the unmatched rule.`,
	);
	process.exit(1);
}

// Both token systems must land, or the cards are off-brand. --bg drives the page
// surface (custom system); --background drives shadcn components.
for (const sentinel of ["--bg:", "--background:"]) {
	if (!aliasedText().includes(sentinel)) {
		console.error(`[css] ✗ expected ${sentinel} among the :root dark aliases — not found`);
		process.exit(1);
	}
}
function aliasedText() { return tokenBlocks.join("\n"); }

const aliased = tokenBlocks
	.map((b) => `:root {\n  ${b}\n}`)
	.join("\n");

css += `
/* ------------------------------------------------------------------
 * design-sync: dark palette aliased onto :root
 * Generated by .design-sync/build-css.mjs from the .dark token blocks above.
 * The site's defaultTheme is "dark" (next-themes writes html.dark at runtime);
 * design surfaces have no such class, so the dark values are promoted to :root.
 * Do not hand-edit -- regenerate with: node .design-sync/build-css.mjs
 * ------------------------------------------------------------------ */
${aliased}

/* \`html body\` (specificity 0,0,2) deliberately outranks the \`body{background:#fff}\`
 * that the converter inlines into every preview card's <head> after the stylesheet
 * links. That white surface is unusable for this DS: in the dark palette
 * --primary is near-white (0 0% 98%), so a default Button renders white-on-white
 * and reads as an empty card. emit.mjs is not forkable by design, and it does not
 * need to be -- specificity wins without touching the output contract. */
html {
  background-color: var(--bg);
}

html body {
  background-color: var(--bg);
  color: var(--text-primary);
}
`;

// Font CSS variables (--font-inter, --font-space-grotesk, ...). They must land
// HERE rather than in the extraFonts stylesheet: the converter keeps only
// @font-face rules from those, so a :root block there is silently dropped and
// every heading falls back to system sans. cssEntry is copied verbatim.
const varsPath = resolve(here, "fonts/font-vars.css");
if (existsSync(varsPath)) {
	css += "\n" + readFileSync(varsPath, "utf8");
	console.error("[css] appended fonts/font-vars.css");
} else {
	console.error("[css] ✗ fonts/font-vars.css missing — run `node .design-sync/build-fonts.mjs` FIRST");
	process.exit(1);
}

writeFileSync(outPath, css);
console.error(`[css] aliased ${tokenBlocks.length} dark token block(s) onto :root`);
console.error(`[css] wrote ${OUT} (${(css.length / 1024).toFixed(1)} KB)`);
